apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: starlight-cooler-credit
  namespace: starlight-cooler-credit
spec:
  rules:
    - host: starlight-cooler-credit.trueberryless.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: starlight-cooler-credit
                port:
                  number: 80

  tls:
    - hosts:
        - starlight-cooler-credit.trueberryless.org
      secretName: starlight-cooler-credit
