apiVersion: v1
kind: Service
metadata:
  name: starlight-cooler-credit
  namespace: starlight-cooler-credit
  annotations:
    cert-manager.io/issuer: acme-issuer
spec:
  selector:
    app: starlight-cooler-credit
  ports:
    - name: http
      port: 80
