name: Deployment

on:
    push:
        branches: [main]
    workflow_dispatch:

# Automatically cancel in-progress actions on the same branch
concurrency:
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
    cancel-in-progress: true

env:
    REGISTRY: docker.io
    IMAGE_OWNER: trueberryless
    IMAGE_NAME: starlight-cooler-credit
    NODE_VERSION: 20

jobs:
    changes:
        name: Filter
        runs-on: ubuntu-latest
        outputs:
            starlight-cooler-credit: ${{ steps.filter.outputs.starlight-cooler-credit }}
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - uses: dorny/paths-filter@v3
              id: filter
              with:
                  filters: |
                      starlight-cooler-credit:
                        - 'packages/starlight-cooler-credit/**'

    changesets:
        name: Changesets
        runs-on: ubuntu-latest
        outputs:
            hasChangesets: ${{ steps.changesets.outputs.hasChangesets }}
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup PNPM
              uses: pnpm/action-setup@v3

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "pnpm"

            - name: Install Dependencies
              run: pnpm i

            - name: Create Release Pull Request
              id: changesets
              uses: changesets/action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.PUBLIC_GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    image-tag:
        name: Image Tag
        runs-on: ubuntu-latest
        outputs:
            IMAGE_TAG: ${{ env.IMAGE_TAG }}
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Read version from package.json
              id: get_version
              run: |
                  VERSION=$(jq -r '.version' package.json)
                  echo "IMAGE_TAG=$VERSION" >> $GITHUB_ENV

    publish:
        needs: [changes, changesets, image-tag]
        # Only run if there is no changeset (i.e. a release), there are changes to the packages/starlight-cooler-credit and the commit message contains '[ci] release' or 'deploy' (workflow_dispatch supported)
        if: (needs.changes.outputs.starlight-cooler-credit == 'true' && needs.changesets.outputs.hasChangesets == 'false' && (contains(github.event.head_commit.message, 'deploy') || contains(github.event.head_commit.message, '[ci] release'))) || github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  registry-url: "https://registry.npmjs.org"
            - run: npm ci
            - run: npm publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    release:
        name: Release
        needs: [image-tag, publish]
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - id: extract-changelog
              uses: sean0x42/markdown-extract@v2.1.0
              with:
                  file: packages/starlight-cooler-credit/CHANGELOG.md
                  pattern: ${{ needs.image-tag.outputs.IMAGE_TAG }}

            - uses: ncipollo/release-action@v1
              with:
                  tag: ${{ env.IMAGE_NAME }}@${{ needs.image-tag.outputs.IMAGE_TAG }}
                  makeLatest: true
                  body: ${{ steps.extract-changelog.outputs.markdown }}
